### ISSUE TITLE
encrypt/decrypt within python code

### ISSUE THREAD

**Issue by joshuisken** [Sets88/ssh-crypt#10]
Now to get an encrypted password as `bytes`:
```
import subprocess
result = subprocess.run("ssh-crypt -e -s testpassword".split(), stdout=subprocess.PIPE)
print(result.stdout)
```
which can be decrypted with:
```
from ssh_crypt import E
super_secret_password = str(E(result.stdout))
```

Would be nice if one could encrypt in python:

```
import getpass
pw = getpass.getpass(prompt='Password: ')

import ssh_crypt.encrypt as encrypt  # or otherwise
encrypted_bytes = encrypt(pw)
```

And then dump/load in json using the standard json module (which may be possible already, but I didn't find a way to properly dump the encrypted password as `E"encrypted_password"`.

**Comment by Sets88** [comment]
Done
https://github.com/Sets88/ssh-crypt/commit/09bd8864b94306bb8809ebd4576e735b6f7235d2
