### ISSUE TITLE
Don't crash with hexlify error if using older python3

### ISSUE THREAD

**Issue by jezzaaa** [Sets88/ssh-crypt#12]
Hi. I presume this is an issue with my version of Python (3.6.8) and I totally understand if you don't want to accommodate it. However I'm not able to upgrade our environment for 12 months, so I'm stuck with the current Python version.

The issue I have is that the older version of binascii.hexlify() that I have doesn't support "sep" and so ssh-crypt doesn't work for me. The end result is:

```
$ ssh-crypt -d -i file.encrypted -f -o default.fifo --key f31a8b8497847d2143b779d7b39ad9b9
Traceback (most recent call last):
  File "/home/x/.local/bin/ssh-crypt", line 8, in <module>
    sys.exit(main())
  File "/home/x/.local/lib/python3.6/site-packages/ssh_crypt/ssh_crypt.py", line 202, in main
    ssh_key = find_filter_key(args.key)
  File "/home/x/.local/lib/python3.6/site-packages/ssh_crypt/utils.py", line 56, in find_filter_key
    elif ssh_filter in binascii.hexlify(key[0].get_fingerprint(), sep=":"):
TypeError: hexlify() takes no keyword arguments
```
I can avoid getting the error if I specify the key name rather than the fingerprint, and it happens to be the first key. But if the key that matches by name is not first, or if I use the fingerprint, it crashes.

I have a work-around for choose_ssh_key() in ssh_crypt/utils.py. I'm not overly familiar with github, so I don't know the best way to submit a patch suggestion, but this is what I'm now using:

```python
def find_filter_key(ssh_filter):
    ssh_filter = ssh_filter.encode()
    filter_keys = []
    for key in [key for key in get_keys() if key[0].name in VALID_SSH_NAME]:
        if ssh_filter in key[1]:
            filter_keys.append(key)
            break ### <-- added
        #elif ssh_filter in binascii.hexlify(key[0].get_fingerprint(), sep=":"):
        elif ssh_filter.replace(b':',b'') in binascii.hexlify(key[0].get_fingerprint()):
            filter_keys.append(key)
            break ### <-- added
    if filter_keys:
        return filter_keys[0][0]
```

Note my two mods:
1. the original "elif" condition (commented out) is adjusted so that the old hexlify() works
2. given that the function only returns the first found key, I added a "break" in both cases where a key is found (although it's not clear to my why you create the filter_keys array if you only ever return one element)

**Comment by Sets88** [comment]
fixed
